"""
Workflow Builder

负责把 ReasoningResult 构建成 Workflow。

WorkflowBuilder 不负责执行，只负责生成 Workflow。
"""

from __future__ import annotations

import uuid

from app.agent.reasoning.reasoning_result import (
    ReasoningResult,
    ReasoningTask,
)

from app.agent.workflow.workflow import Workflow
from app.agent.workflow.workflow_context import WorkflowContext
from app.agent.workflow.workflow_step import (
    WorkflowStep,
    StepType,
)

from app.dispatcher.tool_dispatcher import ToolDispatcher


class WorkflowBuilder:
    """
    Workflow Builder
    """

    def build(
        self,
        question: str,
        reasoning: ReasoningResult,
        conversation_id: str | None = None,
        user_id: str | None = None,
    ) -> Workflow:
        """
        根据 ReasoningResult 创建 Workflow
        """

        workflow_id = str(uuid.uuid4())

        context = WorkflowContext(
            workflow_id=workflow_id,
            question=question,
            conversation_id=conversation_id,
            user_id=user_id,
        )

        context.reasoning_result = reasoning

        workflow = Workflow(
            workflow_id=workflow_id,
            name="Agent Workflow",
            description="Generated by WorkflowBuilder",
            context=context,
        )

        for index, task in enumerate(reasoning.tasks):

            step = self._build_step(
                index=index,
                task=task,
            )

            workflow.add_step(step)

        workflow.ready()

        return workflow

    # =======================================================
    # Build One Step
    # =======================================================

    def _build_step(
        self,
        index: int,
        task: ReasoningTask,
    ) -> WorkflowStep:
        """
        一个 Task -> 一个 WorkflowStep
        """

        step = WorkflowStep(

            step_id=f"step_{index+1}",

            name=task.name,

            step_type=StepType.TOOL if task.tool else StepType.LLM,

            executor=self._build_executor(task),

            inputs=task.args,

            metadata={

                "intent": task.intent,

                "tool": task.tool,

            }

        )

        return step

    # =======================================================
    # Build Executor
    # =======================================================

    def _build_executor(
        self,
        task: ReasoningTask,
    ):
        """
        根据 Task 创建 Executor
        """

        if task.tool is None:

            def llm_executor(
                context,
                **kwargs,
            ):
                """
                预留 LLM 节点。

                后续接入 ModelProvider。
                """

                return None

            return llm_executor

        tool_name = task.tool

        def tool_executor(
            context,
            **kwargs,
        ):

            return ToolDispatcher.dispatch(

                tool_name,

                **kwargs,

            )

        return tool_executor